data = [{'tag_id': 20468, 'tag_name': '红警', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 263089, 'tag_name': '游戏集锦', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 59337, 'tag_name': '红色警戒2', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 962, 'tag_name': '怀旧', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 232, 'tag_name': '红色警戒', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 7160, 'tag_name': '实况解说', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 19890, 'tag_name': '游戏解说', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 14483, 'tag_name': '基地', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 61205, 'tag_name': '幻影', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''},
        {'tag_id': 22999, 'tag_name': '即时战略', 'music_id': '', 'tag_type': 'old_channel', 'jump_url': ''}]
